name: Art_wall
description: Wallpaper App.
version: 1.1.0+2
author: Deepanshu Rawat
environment:
  sdk: ">=2.2.2 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http:
  image_downloader: ^0.19.1
  wallpaper: ^1.0.0
  shared_preferences:
  url_launcher:
  flutter_staggered_grid_view:
  cloud_firestore:
  sqflite:
  intent:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/